In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/NYC_Taxi_ABT.csv')

In [2]:
# Initial exploration of the dataset
df.describe()

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,...,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration_min,speed_mph,pickup_hour,total_fees,net_revenue,net_revenue_per_hour,fee_impact_pct
count,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,...,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06,3.946698e+06
mean,1.787345e+00,1.233373e+00,3.441244e+00,2.710091e+00,1.620718e+02,1.611536e+02,9.466660e-01,1.936859e+01,1.307855e+00,4.963577e-01,...,1.861057e+00,1.207193e-01,5.504911e-01,1.697423e+01,1.102928e+01,1.420994e+01,2.532268e+00,2.560401e+01,1.026528e+02,1.162367e+01
std,4.194354e-01,6.595587e-01,4.121952e+00,1.264134e+01,6.562439e+01,7.000420e+01,6.359776e-01,1.576509e+01,1.842253e+00,4.729320e-02,...,1.090462e+00,4.434926e-01,3.314068e-01,1.339776e+01,6.144650e+00,5.989917e+00,1.242124e+00,1.972887e+01,6.655353e+01,7.462297e+00
min,1.000000e+00,0.000000e+00,1.100000e-01,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e-02,-1.739000e+01,-7.810000e+00,...,0.000000e+00,0.000000e+00,-7.500000e-01,1.000000e+00,1.000000e+00,0.000000e+00,-7.500000e-01,1.010000e+00,5.878739e-01,-1.603935e+00
25%,2.000000e+00,1.000000e+00,1.100000e+00,1.000000e+00,1.220000e+02,1.070000e+02,1.000000e+00,9.300000e+00,0.000000e+00,5.000000e-01,...,0.000000e+00,0.000000e+00,0.000000e+00,8.266667e+00,7.082405e+00,1.000000e+01,1.750000e+00,1.395000e+01,7.731959e+01,4.774898e+00
50%,2.000000e+00,1.000000e+00,1.900000e+00,1.000000e+00,1.610000e+02,1.620000e+02,1.000000e+00,1.420000e+01,0.000000e+00,5.000000e-01,...,2.500000e+00,0.000000e+00,7.500000e-01,1.338333e+01,9.486166e+00,1.500000e+01,3.250000e+00,1.930000e+01,9.290323e+01,1.213592e+01
75%,2.000000e+00,1.000000e+00,3.700000e+00,1.000000e+00,2.330000e+02,2.330000e+02,1.000000e+00,2.260000e+01,2.500000e+00,5.000000e-01,...,2.500000e+00,0.000000e+00,7.500000e-01,2.116667e+01,1.303040e+01,1.900000e+01,3.250000e+00,2.858000e+01,1.156328e+02,1.715040e+01
max,6.000000e+00,9.000000e+00,9.906000e+01,9.900000e+01,2.630000e+02,2.630000e+02,4.000000e+00,1.334020e+03,1.500000e+01,2.214000e+01,...,2.500000e+00,1.750000e+00,1.500000e+00,1.799667e+02,8.000000e+01,2.300000e+01,5.000000e+00,1.342460e+03,2.902500e+04,6.340580e+01

In [3]:
# First 10 rows of the dataset
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,pickup_hour,day_of_week,is_weekend,total_fees,net_revenue,net_revenue_per_hour,fee_impact_pct,fare_tier,trip_length_tier,congestion_level
0,2,2025-01-18 20:53:30,2025-01-18 21:00:47,1,0.97,1,N,238,166,1,...,20,Saturday,True,0.00,13.32,109.729977,0.000000,Low Fare,Short Trip,Heavy Traffic
1,1,2025-01-25 11:12:51,2025-01-25 11:17:57,1,0.60,1,N,50,48,2,...,11,Saturday,True,3.25,7.30,85.882353,30.805687,Low Fare,Short Trip,Heavy Traffic
2,1,2025-01-21 15:09:31,2025-01-21 15:19:02,1,0.80,1,N,236,237,1,...,15,Tuesday,False,2.50,14.15,89.211909,15.015015,Low Fare,Short Trip,Heavy Traffic
3,2,2025-01-11 22:25:45,2025-01-11 22:34:22,2,1.93,1,N,231,68,1,...,22,Saturday,True,3.25,17.12,119.210832,15.954836,Medium Fare,Medium Trip,Moderate Traffic
4,2,2025-01-04 23:37:07,2025-01-04 23:45:58,1,4.44,1,N,137,88,0,...,23,Saturday,True,0.00,35.12,238.101695,0.000000,High Fare,Long Trip,Light Traffic
5,1,2025-01-29 00:31:22,2025-01-29 00:38:27,1,1.10,1,N,140,263,1,...,0,Wednesday,False,2.50,12.98,109.948235,16.149871,Low Fare,Short Trip,Moderate Traffic
6,2,2025-01-30 19:19:28,2025-01-30 19:30:09,1,1.33,1,N,170,230,2,...,19,Thursday,False,3.25,14.70,82.558502,18.105850,Low Fare,Short Trip,Heavy Traffic
7,2,2025-01-23 15:59:29,2025-01-23 16:10:38,1,1.25,1,N,43,43,1,...,15,Thursday,False,3.25,12.90,69.417040,20.123839,Low Fare,Short Trip,Heavy Traffic
8,1,2025-01-23 11:27:08,2025-01-23 11:43:02,1,1.70,1,N,100,113,1,...,11,Thursday,False,3.25,20.30,76.603774,13.800425,Medium Fare,Medium Trip,Heavy Traffic
9,1,2025-01-19 15:42:39,2025-01-19 15:53:35,1,1.20,1,N,163,141,1,...,15,Sunday,True,3.25,12.90,70.792683,20.123839,Low Fare,Short Trip,Heavy Traffic

In [4]:
# Column data types and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3946698 entries, 0 to 3946697
Data columns (total 32 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   str
 2   tpep_dropoff_datetime  str
 3   passenger_count        int64
 4   trip_distance          float64
 5   RatecodeID             int64
 6   store_and_fwd_flag     str
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
 20  duration_min           float64
 21  speed_mph              float64
 22  pickup_hour            int64
 23  day_of_week            str
 24  is_weekend             bool
 25  total_fees             float64
 26  net_revenue            float64
 27  net_revenue_per_hour   float64
 28  fee_impact_pct         float64
 29  fare_tier              str
 30  trip_length_tier       str
 31  congestion_level       str
dtypes: bool(1), float64(17), int64(7), str(7)
memory usage: 937.2 MB

In [5]:
# Number of missing values in each column
df.isnull().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
Airport_fee              0
cbd_congestion_fee       0
duration_min             0
speed_mph                0
pickup_hour              0
day_of_week              0
is_weekend               0
total_fees               0
net_revenue              0
net_revenue_per_hour     0
fee_impact_pct           0
fare_tier                0
trip_length_tier         0
congestion_level         0
dtype: int64

In [6]:
# Percentage of missing values in each column
df.isnull().mean() * 100

VendorID                 0.0
tpep_pickup_datetime     0.0
tpep_dropoff_datetime    0.0
passenger_count          0.0
trip_distance            0.0
RatecodeID               0.0
store_and_fwd_flag       0.0
PULocationID             0.0
DOLocationID             0.0
payment_type             0.0
fare_amount              0.0
extra                    0.0
mta_tax                  0.0
tip_amount               0.0
tolls_amount             0.0
improvement_surcharge    0.0
total_amount             0.0
congestion_surcharge     0.0
Airport_fee              0.0
cbd_congestion_fee       0.0
duration_min             0.0
speed_mph                0.0
pickup_hour              0.0
day_of_week              0.0
is_weekend               0.0
total_fees               0.0
net_revenue              0.0
net_revenue_per_hour     0.0
fee_impact_pct           0.0
fare_tier                0.0
trip_length_tier         0.0
congestion_level         0.0
dtype: float64

In [7]:
# Check for duplicate rows in the dataset
df.duplicated().sum()

np.int64(0)

In [8]:
# Display the minimum values for each numeric column in the dataset
df.min(numeric_only=True)

VendorID                        1
passenger_count                 0
trip_distance                0.11
RatecodeID                      1
PULocationID                    1
DOLocationID                    1
payment_type                    0
fare_amount                  0.01
extra                      -17.39
mta_tax                     -7.81
tip_amount                    0.0
tolls_amount                  0.0
improvement_surcharge         0.0
total_amount                 1.01
congestion_surcharge          0.0
Airport_fee                   0.0
cbd_congestion_fee          -0.75
duration_min                  1.0
speed_mph                     1.0
pickup_hour                     0
is_weekend                  False
total_fees                  -0.75
net_revenue                  1.01
net_revenue_per_hour     0.587874
fee_impact_pct          -1.603935
dtype: object

In [9]:
# Display the maximum values for each numeric column in the dataset
df.max(numeric_only=True)

VendorID                          6
passenger_count                   9
trip_distance                 99.06
RatecodeID                       99
PULocationID                    263
DOLocationID                    263
payment_type                      4
fare_amount                 1334.02
extra                          15.0
mta_tax                       22.14
tip_amount                    550.0
tolls_amount                 115.87
improvement_surcharge           1.0
total_amount                1345.71
congestion_surcharge            2.5
Airport_fee                    1.75
cbd_congestion_fee              1.5
duration_min             179.966667
speed_mph                      80.0
pickup_hour                      23
is_weekend                     True
total_fees                      5.0
net_revenue                 1342.46
net_revenue_per_hour        29025.0
fee_impact_pct            63.405797
dtype: object

In [10]:
# Display the percentiles for each numeric column in the dataset
percentiles = [0.10, 0.25, 0.50, 0.75, 0.90, 0.99]

df_numeric = df.select_dtypes(include=['int', 'float'])

display(df_numeric.quantile(percentiles))

,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,...,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration_min,speed_mph,pickup_hour,total_fees,net_revenue,net_revenue_per_hour,fee_impact_pct
0.10,1.0,1.0,0.70,1.0,68.0,54.0,0.0,7.2,0.00,0.5,...,0.0,0.00,0.00,5.266667,5.296863,6.0,0.75,10.80,66.058021,1.590668
0.25,2.0,1.0,1.10,1.0,122.0,107.0,1.0,9.3,0.00,0.5,...,0.0,0.00,0.00,8.266667,7.082405,10.0,1.75,13.95,77.319588,4.774898
0.50,2.0,1.0,1.90,1.0,161.0,162.0,1.0,14.2,0.00,0.5,...,2.5,0.00,0.75,13.383333,9.486166,15.0,3.25,19.30,92.903226,12.135922
0.75,2.0,1.0,3.70,1.0,233.0,233.0,1.0,22.6,2.50,0.5,...,2.5,0.00,0.75,21.166667,13.030404,19.0,3.25,28.58,115.632808,17.150396
0.90,2.0,2.0,8.70,1.0,239.0,239.0,2.0,38.7,4.25,0.5,...,2.5,0.00,0.75,32.300000,18.941860,21.0,3.25,48.53,147.857143,21.241830
0.99,2.0,4.0,19.27,99.0,263.0,263.0,4.0,70.0,7.50,0.5,...,2.5,1.75,0.75,69.383333,33.356289,23.0,5.00,98.67,251.779141,28.138528

In [11]:
# Display the number of unique values for each column in the dataset
df.nunique()

VendorID                       3
tpep_pickup_datetime     3614373
tpep_dropoff_datetime    3612982
passenger_count               10
trip_distance               3521
RatecodeID                     7
store_and_fwd_flag             2
PULocationID                 258
DOLocationID                 257
payment_type                   5
fare_amount                 9185
extra                         65
mta_tax                       15
tip_amount                  3657
tolls_amount                 998
improvement_surcharge          3
total_amount               15388
congestion_surcharge           4
Airport_fee                    2
cbd_congestion_fee             6
duration_min                8077
speed_mph                 803216
pickup_hour                   24
day_of_week                    7
is_weekend                     2
total_fees                    12
net_revenue                15385
net_revenue_per_hour     1201159
fee_impact_pct             37242
fare_tier                      3
trip_length_tier               3
congestion_level               3
dtype: int64

In [12]:
# Display the number of rows in the dataset
df.shape[0]

3946698

In [13]:
# Display the number of columns in the dataset
df.shape[1]

32

In [14]:
# Display the earliest and latest pickup dates in the dataset
pickup_dates = pd.to_datetime(df['tpep_pickup_datetime'])

print(f"Earliest Pickup: {pickup_dates.min()}")
print(f"Latest Pickup:   {pickup_dates.max()}")

Earliest Pickup: 2007-12-05 18:45:00
Latest Pickup:   2025-11-30 23:59:59